- hosts: 172.16.1.9
  vars:
    tl_dir: /server/tools
    ap_dir: /application
    an_conf: /etc/ansible/conf
  tasks:
    - name: mkdir -p {{ tl_dir }}/tomcat
      file: dest={{ tl_dir }}/tomcat state=directory
    - name: mkdir -p {{ ap_dir }}/tomcat
      file: dest={{ ap_dir }}/tomcat state=directory
    - name: rm -rf {{ tl_dir }}/tomcat/*
      shell: rm -rf {{ tl_dir }}/tomcat/*
    - name: rm -rf {{ ap_dir }}/tomcat/*
      shell: rm -rf {{ ap_dir }}/tomcat/*
    - name: scp -r {{ an_conf }}/tomcat/apache-tomcat-8.5.39.tar.gz root@10.0.0.7:{{ tl_dir }}/tomcat
      copy: src={{ an_conf }}/tomcat/apache-tomcat-8.5.39.tar.gz dest={{ tl_dir }}/tomcat
    - name: scp -r {{ an_conf }}/tomcat/jdk-8u201-linux-x64.rpm root@10.0.0.7:{{ tl_dir }}/tomcat
      copy: src={{ an_conf }}/tomcat/jdk-8u201-linux-x64.rpm dest={{ tl_dir }}/tomcat
    - name: cd {{ tl_dir }}/tomcat;tar -xf apache-tomcat-8.5.39.tar.gz
      shell: cd {{ tl_dir }}/tomcat;tar -xf apache-tomcat-8.5.39.tar.gz
#    - name: cd {{ tl_dir }}/tomcat;rpm -ivh jdk-8u201-linux-x64.rpm
#      shell: cd {{ tl_dir }}/tomcat;rpm -ivh jdk-8u201-linux-x64.rpm
    - name: rm -rf {{ ap_dir }}/tomcat/*
      shell: rm -rf {{ ap_dir }}/tomcat/*
    - name: mv {{ tl_dir }}/tomcat/apache-tomcat-8.5.39 {{ ap_dir }}/tomcat/tomcat
      shell: mv {{ tl_dir }}/tomcat/apache-tomcat-8.5.39 {{ ap_dir }}/tomcat/tomcat
    - name: cd {{ ap_dir }}/tomcat/tomcat/bin;chmod +x *
      shell: cd {{ ap_dir }}/tomcat/tomcat/bin;chmod +x *
    - name: cp -r tomcat tomcat01
      shell: chdir={{ ap_dir }}/tomcat cp -r tomcat tomcat01
    - name: cp -r tomcat tomcat02
      shell: chdir={{ap_dir}}/tomcat cp -r tomcat tomcat02
    - name: cd {{ ap_dir }}/tomcat/tomcat01/bin;chmod +x *
      shell: cd {{ ap_dir }}/tomcat/tomcat01/bin;chmod +x *
    - name: cd {{ ap_dir }}/tomcat/tomcat02/bin;chmod +x *
      shell: cd {{ ap_dir }}/tomcat/tomcat02/bin;chmod +x *
    - name: sed -i 's#8005#8006#g' tomcat01/conf/server.xml
      shell: chdir={{ ap_dir }}/tomcat sed -i 's#8005#8006#g' tomcat01/conf/server.xml
    - name: sed -i 's#8080#8081#g' tomcat01/conf/server.xml
      shell: chdir={{ ap_dir }}/tomcat sed -i 's#8080#8081#g' tomcat01/conf/server.xml
    - name: sed -i 's#8009#8010#g' tomcat01/conf/server.xml
      shell: chdir={{ ap_dir }}/tomcat sed -i 's#8009#8010#g' tomcat01/conf/server.xml
    - name: sed -i 's#8005#8007#g' tomcat02/conf/server.xml
      shell: chdir={{ ap_dir }}/tomcat sed -i 's#8005#8007#g' tomcat02/conf/server.xml
    - name: sed -i 's#8080#8082#g' tomcat02/conf/server.xml
      shell: chdir={{ ap_dir }}/tomcat sed -i 's#8080#8082#g' tomcat02/conf/server.xml
    - name: sed -i 's#8009#8011#g' tomcat02/conf/server.xml
      shell: chdir={{ ap_dir }}/tomcat sed -i 's#8009#8011#g' tomcat02/conf/server.xml
    - name: scp -r {{ an_conf }}/tomcat/ROOT.war root@10.0.0.9:{{ ap_dir }}/tomcat/tomcat/webapps
      copy: src={{ an_conf }}/tomcat/ROOT.war dest={{ ap_dir }}/tomcat/tomcat/webapps
    - name: scp -r {{ an_conf }}/tomcat/ROOT.war root@10.0.0.9:{{ ap_dir }}/tomcat/tomcat01/webapps
      copy: src={{ an_conf }}/tomcat/ROOT.war dest={{ ap_dir }}/tomcat/tomcat01/webapps
    - name: scp -r {{ an_conf }}/tomcat/ROOT.war root@10.0.0.9:{{ ap_dir }}/tomcat/tomcat02/webapps
      copy: src={{ an_conf }}/tomcat/ROOT.war dest={{ ap_dir }}/tomcat/tomcat02/webapps
    - name: chdir={{ ap_dir }}/tomcat/tomcat/webapps/  mv ROOT ROOTBAK
      shell: chdir={{ ap_dir }}/tomcat/tomcat/webapps/  mv ROOT ROOTBAK
    - name: chdir={{ ap_dir }}/tomcat/tomcat02/webapps/  mv ROOT ROOTBAK
      shell: chdir={{ ap_dir }}/tomcat/tomcat02/webapps/  mv ROOT ROOTBAK
    - name: chdir={{ ap_dir }}/tomcat/tomcat01/webapps/  mv ROOT ROOTBAK
      shell: chdir={{ ap_dir }}/tomcat/tomcat01/webapps/  mv ROOT ROOTBAK
    - name: chdir={{ ap_dir }}/tomcat/tomcat/bin/ nohup ./catalina.sh start &
      shell: chdir={{ ap_dir }}/tomcat/tomcat/bin/ nohup ./catalina.sh start &
    - name: chdir={{ ap_dir }}/tomcat/tomcat01/bin/ nohup ./catalina.sh start &
      shell: chdir={{ ap_dir }}/tomcat/tomcat01/bin/ nohup ./catalina.sh start &
    - name: chdir={{ ap_dir }}/tomcat/tomcat02/bin/ nohup ./catalina.sh start &
      shell: chdir={{ ap_dir }}/tomcat/tomcat02/bin/ nohup ./catalina.sh start &



